/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author axioo
 */
public class tiga extends javax.swing.JFrame {

    /**
     * Creates new form tiga
     */
    public tiga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        mkn1 = new javax.swing.JLabel();
        mkn2 = new javax.swing.JLabel();
        mkn3 = new javax.swing.JLabel();
        mkn4 = new javax.swing.JLabel();
        mkn5 = new javax.swing.JLabel();
        mkn6 = new javax.swing.JLabel();
        mkn7 = new javax.swing.JLabel();
        mkn8 = new javax.swing.JLabel();
        mkn9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        pesan_mkn = new javax.swing.JButton();
        hitungmkn = new javax.swing.JButton();
        ComboBoxmkn = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txthargamkn = new javax.swing.JTextField();
        txtjumlahharga = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtjumlahbeli1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 210, 114));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(400, 550));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 550));

        jPanel1.setBackground(new java.awt.Color(255, 210, 114));
        jPanel1.setPreferredSize(new java.awt.Dimension(359, 1300));

        jPanel2.setBackground(new java.awt.Color(91, 50, 0));

        jButton2.setBackground(new java.awt.Color(222, 184, 135));
        jButton2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 30)); // NOI18N
        jButton2.setText("FOOD");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        mkn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/11 (1).png"))); // NOI18N

        mkn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/22 (1).png"))); // NOI18N

        mkn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/33 (1).png"))); // NOI18N

        mkn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.png"))); // NOI18N

        mkn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5.png"))); // NOI18N

        mkn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/6.png"))); // NOI18N

        mkn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/7.png"))); // NOI18N

        mkn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8.png"))); // NOI18N

        mkn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reservasi Tempat & Menu Makanan (1).png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reservasi Tempat & Menu Makanan (2).png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(204, 153, 0));
        jLabel1.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        jLabel1.setText("SILAHKAN LIST PESANAN ANDA ");
        jLabel1.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        jLabel2.setText("DIBAWAH SINI  -Yummy's Restaurant-");

        jButton4.setBackground(new java.awt.Color(222, 184, 135));
        jButton4.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jButton4.setText("Menu Minuman");
        jButton4.setBorder(null);
        jButton4.setPreferredSize(new java.awt.Dimension(124, 27));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        pesan_mkn.setBackground(new java.awt.Color(222, 184, 135));
        pesan_mkn.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        pesan_mkn.setText("Pesan");
        pesan_mkn.setBorder(null);
        pesan_mkn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesan_mknMouseClicked(evt);
            }
        });
        pesan_mkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan_mknActionPerformed(evt);
            }
        });

        hitungmkn.setBackground(new java.awt.Color(222, 184, 135));
        hitungmkn.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        hitungmkn.setText("Hitung");
        hitungmkn.setBorder(null);
        hitungmkn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hitungmknMouseClicked(evt);
            }
        });
        hitungmkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungmknActionPerformed(evt);
            }
        });

        ComboBoxmkn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nasi Lemak Yummy's", "Nasi Goreng Yummy", "Ikan Pedas Manis + Nasi", "Bakso Urat Yummy ", "Ramen Yummy's ", "Spagetti Yummy's", "Kimchii Yummy's", "Sushi nori Yummy", "Chicken Cruncy ", "Ayam Bakar Yummy + Nasi", "Seafood Yummy's + Nasi", "Paket 1 (Nasi + Ikan Pedas + Ayam Bakar)", "Paket 2 (Nasi Goreng+ Ayam )", "Paket 3 (Nasi + Seafood + Kimchii)", "Paket 4 (Ramen + Spagetti)", "Paket 5 (Sushi + Bakso)" }));
        ComboBoxmkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxmknActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jLabel13.setText("Makanan   :");

        jLabel14.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jLabel14.setText("@ Harga  :");

        txtjumlahharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahhargaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jLabel12.setText("Total      :");

        jLabel15.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        jLabel15.setText("Porsi :");

        bayar.setBackground(new java.awt.Color(222, 184, 135));
        bayar.setFont(new java.awt.Font("Kristen ITC", 1, 10)); // NOI18N
        bayar.setText("Bayar");
        bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayarMouseClicked(evt);
            }
        });
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mkn5)
                        .addGap(18, 18, 18)
                        .addComponent(mkn6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mkn3)
                        .addGap(18, 18, 18)
                        .addComponent(mkn4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mkn1)
                        .addGap(18, 18, 18)
                        .addComponent(mkn2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mkn7)
                            .addComponent(mkn9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addComponent(mkn8))))
                .addGap(0, 31, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hitungmkn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesan_mkn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxmkn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txthargamkn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtjumlahharga, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtjumlahbeli1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mkn2)
                    .addComponent(mkn1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mkn3)
                    .addComponent(mkn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mkn5)
                    .addComponent(mkn6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mkn7)
                    .addComponent(mkn8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mkn9)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxmkn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthargamkn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjumlahbeli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjumlahharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitungmkn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesan_mkn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        Byr.Instancer.hsl.setText(txtjumlahharga.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarMouseClicked

    private void txtjumlahhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahhargaActionPerformed

    }//GEN-LAST:event_txtjumlahhargaActionPerformed

    private void ComboBoxmknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxmknActionPerformed
        // TODO add your handling code here:
        switch (ComboBoxmkn.getSelectedIndex()) {
            case 1:
            txthargamkn.setText(String.valueOf(18000));
            break;
            case 2:
            txthargamkn.setText(String.valueOf(17000));
            break;
            case 3:
            txthargamkn.setText(String.valueOf(24000));
            break;
            case 4:
            txthargamkn.setText(String.valueOf(20000));
            break;
            case 5:
            txthargamkn.setText(String.valueOf(28000));
            break;
            case 6:
            txthargamkn.setText(String.valueOf(25000));
            break;
            case 7:
            txthargamkn.setText(String.valueOf(22000));
            break;
            case 8:
            txthargamkn.setText(String.valueOf(28000));
            break;
            case 9:
            txthargamkn.setText(String.valueOf(28000));
            break;
            case 10:
            txthargamkn.setText(String.valueOf(27000));
            break;
            case 11:
            txthargamkn.setText(String.valueOf(45000));
            break;
            case 12:
            txthargamkn.setText(String.valueOf(49000));
            break;
            case 13:
            txthargamkn.setText(String.valueOf(52000));
            break;        
            case 14:
            txthargamkn.setText(String.valueOf(36000));
            break;        
            case 15:
            txthargamkn.setText(String.valueOf(47000));
            break;        
    }//GEN-LAST:event_ComboBoxmknActionPerformed
}
    private void hitungmknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungmknActionPerformed
        Double harga,jbeli,hasil;
        harga=Double.parseDouble(txthargamkn.getText());
        jbeli=Double.parseDouble(txtjumlahbeli1.getText());
        hasil=harga*jbeli;
        txtjumlahharga.setText(String.valueOf(hasil));
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungmknActionPerformed

    private void hitungmknMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitungmknMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungmknMouseClicked

    private void pesan_mknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan_mknActionPerformed
        new Byr().setVisible(true);
        /**bil2 = Double.parseDouble(angka);
        jumlah = bil1*bil2;
        angka = Double.toString(jumlah);
        display.setText(angka);**/
        // TODO add your handling code here:
    }//GEN-LAST:event_pesan_mknActionPerformed

    private void pesan_mknMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesan_mknMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pesan_mknMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        IU tmptmnm = new IU ();
        tmptmnm.show();

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxmkn;
    private javax.swing.JButton bayar;
    private javax.swing.JButton hitungmkn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mkn1;
    private javax.swing.JLabel mkn2;
    private javax.swing.JLabel mkn3;
    private javax.swing.JLabel mkn4;
    private javax.swing.JLabel mkn5;
    private javax.swing.JLabel mkn6;
    private javax.swing.JLabel mkn7;
    private javax.swing.JLabel mkn8;
    private javax.swing.JLabel mkn9;
    private javax.swing.JButton pesan_mkn;
    private javax.swing.JTextField txthargamkn;
    private javax.swing.JTextField txtjumlahbeli1;
    public javax.swing.JTextField txtjumlahharga;
    // End of variables declaration//GEN-END:variables
}
